services:
  patching-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: patching-bot:latest
    container_name: patching-bot
    ports:
      - "5000:5000"
    volumes:
      - patch_storage:/home/node/.n8n
      - ./uploads:/app/uploads
      - ./watch_dir:/data/shared/patching
    environment:
      - DEBUG=True
      - AUTO_START_MONITORING=False
      - OLLAMA_URL=http://host.docker.internal:11434/api/generate
      - AI_PROVIDER=vllm
      - OLLAMA_MODEL=mistral
      - VLLM_CHAT_COMPLETIONS_URL=https://vllm.rangeresources.com/v1/chat/completions 
      - VLLM_MODELS_URL=https://vllm.rangeresources.com/v1/models 
      - VLLM_MODEL=Qwen/Qwen3-30B-A3B-FP8
      - VLLM_VERIFY_SSL=False 
      - VLLM_API_KEY=123456789
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  patch_storage: